# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Stochastic Life
tagline:          'Too many interests, too little time!'
description:      "Tarun Vangani's Blog"
url:              https://stochastic.life
baseurl:          /

author:
  name:           'Tarun Kumar Vangani'
  url:            http://twitter.com/reachtarunhere

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/reachtarunhere/reachtarunhere.github.io

gems:
  - jekyll-seo-tag

future: true
